# Generated by Django 3.2.7 on 2021-12-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flopblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_pros', models.TextField(max_length=500)),
                ('movie_cons', models.TextField(max_length=500)),
                ('overall_review', models.CharField(max_length=1000)),
                ('rating_by_ten', models.IntegerField(default=0)),
            ],
        ),
    ]
