# Generated by Django 3.2.7 on 2021-12-08 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_flopblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='flopblog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
